FROM golang:1.17-alpine
WORKDIR /app
RUN apk update && \
    apk add git bash && \
    rm /var/cache/apk/*
RUN CGO_ENABLED=0 go get -u github.com/pressly/goose/cmd/goose
COPY ./app/migrations /migrations/
ENTRYPOINT ["/go/bin/goose"]
