FROM golang:1.18.2-alpine
WORKDIR /app
RUN apk update && \
    apk add git bash && \
    rm /var/cache/apk/*
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.5.3
COPY ./migrations /migrations/
ENTRYPOINT ["/go/bin/goose"]
