FROM golang:1.18.0-alpine

# Add required packages
RUN apk add --update git curl bash

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV CGO_ENABLED 0

ADD . .

RUN go install github.com/revel/cmd/revel@v1.0.0

# Run revel app
ENTRYPOINT revel run
