FROM golang:1.18.2-alpine

# Add required packages
RUN apk add --update git curl bash

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV CGO_ENABLED 0

RUN go install github.com/revel/cmd/revel@v1.1.0

ADD . .

# Run revel app
ENTRYPOINT revel run
