FROM alpine:3.13

RUN apk update && \
    apk add curl && \
    rm /var/cache/apk/*

RUN curl -L -o /go/bin/goose https://github.com/pressly/goose/releases/download/v2.6.0/goose-linux64 && \
    chmod +x /go/bin/goose

COPY ./app/migrations /migrations/

ENTRYPOINT ["/go/bin/goose"]
