apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apisim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apisim
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
