version: '3.9'

services:
  apisim:
    image: ektowett/apisim:v1.1.0
    ports:
      - 4027:4027
    environment:
      - ENV=dev
      - PORT=4027
      - DB_URL=postgres://apisim:apisim@postgres/apisim?sslmode=disable
      - REDIS_URL=redis://:MDNcVb924a@redis:6379

  workwebui:
    image: ektowett/workwebui:latest
    ports:
      - 5040:5040
    depends_on:
      - redis
    environment:
      - REDIS_NAMESPACE=apisim
      - REDIS_HOST=redis://:MDNcVb924a@redis:6379

  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/apisim/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=apisim
      - POSTGRES_USER=apisim
      - POSTGRES_DB=apisim

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass MDNcVb924a
