---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: live

resources:
- namespace.yaml
- ../../base

patchesStrategicMerge:
  - rollout-replica.yaml
  # - hpa.yaml

images:
  - name: gcr.io/legacy-poc-work/apisim
    newTag: main-acd82b1
  - name: gcr.io/legacy-poc-work/apisim-migrate
    newTag: main-acd82b1
